### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chschilling** [eleven6/rct-power#1]
Hey,

I know it is quite old but I am asking nevertheless for support:
I try to use your scripts to implement rct in openhab as you described on 
https://community.openhab.org/t/binding-request-rct-power-invertor/95121/5
I am using username/password and updated the vars:
mqttc = mqtt.Client() # the mqtt client connection
mqttc.username_pw_set = ('mqttuser', 'mqttpassword')

I don't know exactly how to get the data to my mosquitto, should rct-receiver.py run permanently?

Following task in rctmon.py is failing 
```
# will be executed when mqttc.connect receives response
def on_connect(client, userata, flags, rc):
    global mqtt_topic # make topic available
    global mqttc
    
    if rc==0:
       print("succesfully connected...")
       mqttc.subscribe(mqtt_topic)
    else:
       print("connection could not be established...")
       sys.exit(1)
```
Maybe a short hint how to use that scripts would be awesome :)

**Comment by eleven6** [comment]
Hey @chschilling, yes the rct-mon.oh needs
To be run regularly. I am having a cron right now running every 5min - thinking of moving to https://jupyter.org/ to Code and run my Python scripts out of a K3S
Kubernetes cluster.

there is as well a possibly more mature RCT/MQTT Solution available from https://github.com/brainboutique/rct-mqtt

need to check it out yet.

best, Jens

**Comment by chschilling** [comment]
Thanks for the response, but rct-mqtt is not supporting authentication so far.
What is the "rct-receiver.py for?
and how do they corelate?

**Comment by eleven6** [comment]
You can simply add the MQTT Auth where the connection is made, pretty sure there is a. Easy documentation available somewhere.

or you switch to the other solution I linked in my previous answer.

rct-receiver is just listening and printing what is being sent -> I use it for debugging only.

**Comment by chschilling** [comment]
Ok Stupid me...
I got the authentication part but was to dump to copy and paste -.-

Thanks nevertheless :D
